#!/bin/bash

sudo apt-get install -y glance-client python-novaclient

export OS_TENANT_NAME=$1
export OS_USERNAME=$1
export OS_PASSWORD=$2
export OS_AUTH_URL="http://123.126.53.170:5000/v2.0/"

tar zxvf ubuntu-10.04-server-cloudimg-amd64.tar.gz
ramdisk_id=`glance add disk_format=ari container_format=ari is_public=True name="Ubuntu-10.04-Server-LTS-amd64-loader" < lucid-server-cloudimg-amd64-loader| tail -n1 | awk '{print $NF}'`
kernel_id=`glance add disk_format=aki container_format=aki is_public=True name="Ubuntu-10.04-Server-LTS-amd64-kernel" < lucid-server-cloudimg-amd64-vmlinuz-virtual| tail -n1 | awk '{print $NF}'`
glance add disk_format=ami container_format=ami is_public=True ramdisk_id=$ramdisk_id kernel_id=$kernel-id name="Ubuntu-10.04-Server-LTS-amd64" < lucid-server-cloudimg-amd64.img
